services:
  web:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    networks:
      - notifier-network

  db:
    image: postgres:16.4
    env_file: .env
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    restart: always
    networks:
      - notifier-network

volumes:
  postgres_data:

networks:
  notifier-network:
    driver: bridge
