services:
  metabase_db:
    image: postgres:16.4
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - mb_db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - notifier-network

  metabase:
    image: metabase/metabase-enterprise:v1.51.1.2
    container_name: metabase-with-clickhouse-driver
    hostname: metabase
    volumes:
      - ./clickhouse.metabase-driver.jar:/plugins/clickhouse.jar
      - metabase_data:/metabase-data
    env_file: .env
    ports:
      - "3001:3000"
    networks:
      - notifier-network
    depends_on:
      - metabase_db
    healthcheck:
      test: curl --fail -X GET -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 10
    restart: always

networks:
  notifier-network:
    external: true

volumes:
  metabase_data:
  mb_db_data:
