# Generated by Django 5.1.4 on 2025-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_workspace_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="owner",
        ),
    ]
