# Generated by Django 5.1.4 on 2025-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0004_remove_workspace_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
