# Generated by Django 5.1.4 on 2025-01-17 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RolePermission",
        ),
    ]
