# Generated by Django 5.1.4 on 2025-01-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seat_user_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='seat',
            table='seats',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
